### ISSUE TITLE
Set all day

### ISSUE THREAD

**Issue by jaredlt** [jaredlt/add_to_calendar#18]
Ability to set some kind of `allday: true` flag?

- handle/ignore times in date/time objects
- handle multiple days
- Yahoo `dur=allday` but unverified - TEST THIS

**Comment by jaredlt** [comment]
@ixdf-bot thank you! I discovered that repo way later than I wished. Went through a _lot_ of pain on my own beforehand. Are you actually a bot? :) If not, do you have a need for this feature? I don't need it in my own projects but if someone else does I would be willing to implement it.

**Comment by jaredlt** [comment]
@ixdf-bot gotcha! Yeah, your repo has been really helpful for me, particularly for Outlook / Office 365 - so thank you 👍 

Happy to contribute back if I discover anything. You have already helped me with a few edge cases [here](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/issues/17) and [here](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/issues/14) so thanks again :)

**Comment by ryjones** [comment]
Looking at implementations, the main one seems to be:
`BEGIN:VEVENT
X-GIOIDS:Event:1031771
UID:vsgu.1610183640601153857.oxEX@lists.hyperledger.org
DTSTAMP:20210109T091428Z
ORGANIZER;CN=maintainers@lists.hyperledger.org Group:mailto:maintainers@l
 ists.hyperledger.org
**DTSTART:20210117
DTEND:20210124**
SUMMARY:[Hyperledger Maintainers] One Week Test event
SEQUENCE:0
END:VEVENT`

**Comment by jaredlt** [comment]
Thank you @ryjones :) Saves me digging into the iCalendar spec again.

**Comment by ryjones** [comment]
There is an issue with Google's handling of shared ICS that causes me a lot of heartburn. Someday, in my copious free time, I'll code a way to:

- specify calendars in yaml
- render them as ics
- push them into Google directly

**Comment by andyjeffries** [comment]
I'd really appreciate this feature @jaredlt , I'm wanting to use it in a live project for a local school that I run free of charge.

**Comment by jaredlt** [comment]
@andyjeffries the local school reference is just the kind of ~~guilt trip~~incentive I need :) Let me see if I can find some time on the weekend.

Can you share a bit more about your use case? Is it single day all day, or multi-day all day, or both?

**Comment by andyjeffries** [comment]
Glad I could help with motivation 😉. There's no urgency though, they're happy I've added it as it stands.

Potentially both. 

So the use-case is that they have a public calendar of events. Now, I'm creating an event show page for each event that just lists the title, date/time, a QR code to the same page (so they can drag/drop them out in to word documents and newsletters/etc) and then the add to calendar links.

I can imagine that a "half-term" event would be a multi-day all day event, and that a "start of term" would be a single day all day event.

Hope that helps, but feel free to ask anything further.

**Comment by andyjeffries** [comment]
![Screenshot 2023-04-27 at 08 48 24](https://user-images.githubusercontent.com/22904/234795452-fa3d84a7-6ab4-4317-9be7-0d79fa8a7025.png)

An example of what I'm talking about. That's actually a multi-day event, but obviously on the site we only show the start of half-term (as all parents know how long it's for)

**Comment by jaredlt** [comment]
@andyjeffries can you test this out for me in `0.3.0`? You pass an `all_day: true` attribute like so:

```ruby
AddToCalendar::URLs.new(
        start_datetime: Time.new(2023,12,12,13,30,00,0), 
        title: "Christmas party!", 
        timezone: 'Europe/London',
        all_day: true
      )
```

I added some notes to the readme:

> - Defaults to false.
> - When set to true the times will be ignored.
> - If no end_datetime provided it will be a single day event.
> - When providing end_datetime, use the final day of the event (eg. 1 day event start: 2023-05-01, end: 2023-05-01; 3 day event start: 2023-05-01, end: 2023-05-03).
> - Some calendars require you to specify the day after as the end date which feels counterintuitive, this Gem takes care of that for you.

I now regret some of my original naming (looking at you `start_datetime` and `end_datetime`)... At some point I will also [better handle duck typing](https://github.com/jaredlt/add_to_calendar/issues/19) so that you don't have to continue to put a Time class into these attributes 😅 

Feedback welcome!

**Comment by andyjeffries** [comment]
That works perfectly for me! Many thanks for sorting it so fast!
